### ISSUE TITLE
fix instance utilization

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy#1051]
The steady state instance count for our frontend service on App Engine suddenly increased from 1 to 2 recently, on 6/17:

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/778068/123658263-657be380-d7e6-11eb-89b4-a8e334e0c5f8.png">

The timing coincided with a deploy, but we generally deploy multiple times a week, and we haven't made any architectural or utilization changes recently, so I kind of doubt this was self inflicted. The same thing happened to Bridgy Fed a week later, which I haven't deployed or made any other changes to since April:

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/778068/123658491-a116ad80-d7e6-11eb-8805-9ef33584cff7.png">

Maybe a scheduler change on Google's side. Ugh. I'll ask on the group.

**Comment by snarfed** [comment]
Posted on the group: https://groups.google.com/g/google-appengine/c/EvX2duPXMXI

**Comment by snarfed** [comment]
I tried updating the auto scaling config in [`app.yaml`](https://github.com/snarfed/bridgy/blob/main/app.yaml) to this:

```
automatic_scaling:
  max_idle_instances: 1
  target_cpu_utilization: .9
  min_pending_latency: 500ms
  max_concurrent_requests: 30
```

Seems like it's helping a bit so far.
